function LoopThroughMultipleDataFolders ()
%User inputs all folders to run the ROI analysis and export raw binding curve data
list_of_folders={'E:\ISS data\Time Domain\BMK-D3\mCerulean3-BclXL-ActA\20160520\A8_Untransfected',...
    'E:\ISS data\Time Domain\BMK-D3\mCerulean3-BclXL-ActA\20160520\A1_Venus-ActA',...
    'E:\ISS data\Time Domain\BMK-D3\mCerulean3-BclXL-ActA\20160520\A2_Venus-BIK',...
    'E:\ISS data\Time Domain\BMK-D3\mCerulean3-BclXL-ActA\20160520\A3_Venus-BIKL61G',...
    'E:\ISS data\Time Domain\BMK-D3\mCerulean3-BclXL-ActA\20160520\A4_Venus-BIK-ActA',...
    'E:\ISS data\Time Domain\BMK-D3\mCerulean3-BclXL-ActA\20160520\A5_Venus-BIK-cb5',...
    'E:\ISS data\Time Domain\BMK-D3\mCerulean3-BclXL-ActA\20160520\A6_Venus-Beclin1',...
    'E:\ISS data\Time Domain\BMK-D3\mCerulean3-BclXL-ActA\20160520\A7_Venus-cb5'};


for i = 1:numel(list_of_folders)
    data_path = list_of_folders{i}; 
    disp(data_path)
    ISSWatershedSegmentation(data_path);
end

fprintf('The "LoopThroughMultipleDataFolders" Analysis is complete');
end